[tools]
lune = "lune-org/lune@0.10.1"
rojo = "rojo-rbx/rojo@7.5.1"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.29.0"
stylua = "JohnnyMorganz/stylua@2.1.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.53.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
