[package]
name = "egomoose/prospector"
description = "https://github.com/EgoMoose/prospector"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dependencies]
Deque = "egomoose/deque@0.1.1"
Trove = "sleitnick/trove@1.4.0"
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"