name: Release

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --draft --verify-tag --title ${{ github.ref_name }}

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: "Run wally install"
        run: |
          lune run wally-install

      - name: Build rbxm
        run: |
          rojo build build.project.json --output prospector-${{ github.ref_name }}.rbxm

      - name: Create Archive and Upload to Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} prospector-${{ github.ref_name }}.rbxm
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: prospector-${{ github.ref_name }}.rbxm